spring:
  config:
    activate:
      on-profile: docker
  application:
    name: tsgfeedbackapi
  
  kafka:
    bootstrap-servers: kafka:29092
  
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080

