spring:
  application:
    name: tsgfeedbackapi

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1

  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080